CREATE DATABASE x
GO

USE x
GO

CREATE TABLE Accounts(
	UserName nvarchar(50) NOT NULL,
	PassWord nvarchar(50) NOT NULL,
	FullName nvarchar(50) NOT NULL,
	DateCreated date NOT NULL,
	Role nvarchar(50) NOT NULL,

)
GO

CREATE TABLE Bill(
	Code nvarchar(50) NOT NULL,
	Product nvarchar(100) NOT NULL,
	Amount int NOT NULL,
	IntoMoney nvarchar(100) NOT NULL
)
GO

CREATE TABLE Classify(
	ID nvarchar(50) NOT NULL,
	Classify nvarchar(100) NOT NULL
)
GO

CREATE TABLE Information(
	Name nvarchar(100) NOT NULL,
	Date nvarchar(50) NOT NULL,
	Time nvarchar(50) NOT NULL,
	TotalMoney nvarchar(100) NOT NULL,
	Money nvarchar(100) NOT NULL,
	Surplus nvarchar(100) NOT NULL
)
GO

CREATE TABLE iThongKe(
	tonghoadon nchar(20) NOT NULL,
	tongtien nchar(100) NOT NULL,
	tungay nchar(30) NOT NULL,
	denngay nchar(30) NOT NULL
)
GO

CREATE TABLE NhanVien(
	Position nchar(50) NOT NULL,
	Level int NOT NULL,
	EmployeeCode nchar(50) NOT NULL,
	FullName nchar(100) NOT NULL,
	YearofBirth date NOT NULL,
	Sex nchar(10) NOT NULL,
	Address nchar(200) NOT NULL,
	Phone nchar(20) NOT NULL,
	Email nchar(50) NOT NULL,
	Payroll nchar(100) NOT NULL
)
GO

CREATE TABLE Orders(
	ID nchar(10) NOT NULL,
	Customer nchar(50) NOT NULL,
	Address nchar(200) NOT NULL,
	Phone nchar(20) NOT NULL,
	Product nchar(100) NOT NULL,
	Amount int NOT NULL,
	Price nchar(100) NOT NULL,
	WarrantyPeriod nchar(100) NOT NULL,
	intoMoney nchar(100) NOT NULL,
	Date date NOT NULL,
	PaymentMethods nchar(100) NOT NULL
)
GO

CREATE TABLE Position(
	ID nchar(20) NOT NULL,
	Position nchar(200) NOT NULL,
	Payroll nchar(200) NOT NULL
)
GO

CREATE TABLE Producer(
	ID nchar(30) NULL,
	ProducerName nchar(50) NULL,
	Address nchar(100) NULL,
	Phone nchar(20) NULL,
	Email nchar(50) NULL
)
GO

CREATE TABLE Products(
	ID nchar(30) NOT NULL,
	Classify nchar(30) NOT NULL,
	Name nchar(100) NOT NULL,
	Producer nchar(100) NOT NULL,
	WarrantyPeriod int NOT NULL,
	SingleTime nchar(30) NOT NULL,
	QuantityRemaining int NOT NULL,
	Unit nchar(30) NOT NULL,
	Price nchar(100) NOT NULL,
	Path nchar(500) NOT NULL
)
GO

CREATE TABLE Revenue(
	Name nvarchar(100) NOT NULL,
	Date date NOT NULL,
	Time nvarchar(30) NOT NULL,
	TotalMoney nvarchar(100) NOT NULL,
	Money nvarchar(100) NOT NULL,
	Surplus nvarchar(100) NOT NULL
)
GO

CREATE TABLE ThongKe(
	Name nvarchar(100) NOT NULL,
	Date date NOT NULL,
	Time nvarchar(30) NOT NULL,
	TotalMoney nvarchar(100) NOT NULL,
	Money nvarchar(100) NOT NULL,
	Surplus nvarchar(100) NOT NULL
)
GO

INSERT Accounts (UserName, PassWord, FullName, DateCreated, Role) VALUES (N'Admin', N'123', N'Dương Thanh Trung', CAST(N'2018-01-22' AS Date), N'Admin')
INSERT Accounts (UserName, PassWord, FullName, DateCreated, Role) VALUES (N'User', N'123', N'Nguyễn Hoàng Lộc', CAST(N'2018-02-20' AS Date),N'Bán hàng')
INSERT Accounts (UserName, PassWord, FullName, DateCreated, Role) VALUES (N'tramanh96', N'12345', N'Cao Vũ Trâm Anh', CAST(N'2018-04-30' AS Date),N'Bán hàng')
INSERT Accounts (UserName, PassWord, FullName, DateCreated, Role) VALUES (N'cuong2018', N'123456', N'Dương Thanh Trung', CAST(N'2018-04-30' AS Date),N'Bán hàng')
INSERT Accounts (UserName, PassWord, FullName, DateCreated, Role) VALUES (N'cuongcu', N'****', N'Dương Thanh Trung', CAST(N'2018-05-02' AS Date),N'Bán hàng')
INSERT Accounts (UserName, PassWord, FullName, DateCreated, Role) VALUES (N'tramanh96', N'123456789', N'Dương Thanh Trung', CAST(N'2018-04-30' AS Date),N'Bán hàng')
INSERT Accounts (UserName, PassWord, FullName, DateCreated, Role) VALUES (N'nhungoc', N'1234', N'Lâm Như Ngọc', CAST(N'2018-05-08' AS Date),N'Bán hàng')
INSERT Accounts (UserName, PassWord, FullName, DateCreated, Role) VALUES (N'Manager', N'123', N'Quản lý', CAST(N'2018-05-14' AS Date),N'Manager')
GO
INSERT Bill (Code, Product, Amount, IntoMoney) VALUES (N'HW001', N'Hard Drive Kingston 120GB', 3, N'10,500,000 VND')
GO
INSERT Classify (ID, Classify) VALUES (N'BP001     ', N'Backpack                                          ')
INSERT Classify (ID, Classify) VALUES (N'HD01      ', N'Hard Drive                                        ')
INSERT Classify (ID, Classify) VALUES (N'HK457     ', N'Micro SD                                          ')
INSERT Classify (ID, Classify) VALUES (N'HP001     ', N'Headphone                                         ')
INSERT Classify (ID, Classify) VALUES (N'HS01      ', N'Radiator Fan                                      ')
INSERT Classify (ID, Classify) VALUES (N'IN001     ', N'CPU                                               ')
INSERT Classify (ID, Classify) VALUES (N'KB01      ', N' Keyboard                                         ')
INSERT Classify (ID, Classify) VALUES (N'TB01      ', N'The Battery                                       ')
INSERT Classify (ID, Classify) VALUES (N'TN001     ', N'Ram                                               ')
INSERT Classify (ID, Classify) VALUES (N'TN002     ', N'USB                                               ')
INSERT Classify (ID, Classify) VALUES (N'TN003     ', N'Mouse                                             ')
INSERT Classify (ID, Classify) VALUES (N'GSF01', N'Gậy Selfie')
INSERT Classify (ID, Classify) VALUES (N'KK009', N'Pin Đồng Hồ')
INSERT Classify (ID, Classify) VALUES (N'NN001', N'Cáp Sạc')
GO
INSERT Information (Name, Date, Time, TotalMoney, Money, Surplus) VALUES (N'Điện Tử Số 1', N'11/05/2020', N'16:32:17', N'10,500,000 VND', N'12,312,313,123 VND', N'12,301,813,123 VND')
GO
INSERT iThongKe (tonghoadon, tongtien, tungay, denngay) VALUES (N'8                   ', N'60,150,000 VND                                                                                      ', N'01/05/2018                    ', N'09/05/2018                    ')
GO
INSERT NhanVien (Position, Level, EmployeeCode, FullName, YearofBirth, Sex, Address, Phone, Email, Payroll) VALUES (N'Giám Đốc                                          ', 2, N'GD001                                             ', N'Dương Thanh Trung                                                                                   ', CAST(N'1996-03-15' AS Date), N'Nam       ', N'Hậu Giang                                                                                                                                                                                               ', N'01684342451         ', N'trung96@gmail.com                                 ', N'40,000,000 VND                                                                                      ')
INSERT NhanVien (Position, Level, EmployeeCode, FullName, YearofBirth, Sex, Address, Phone, Email, Payroll) VALUES (N'Kế Toán                                           ', 5, N'KT001                                             ', N'Nguyễn Hoàng Lộc                                                                                    ', CAST(N'2018-02-28' AS Date), N'Nam       ', N'Sóc Trăng                                                                                                                                                                                               ', N'09090909090         ', N'loc@gmail.com                                     ', N'25,000,000 VND                                                                                      ')
INSERT NhanVien (Position, Level, EmployeeCode, FullName, YearofBirth, Sex, Address, Phone, Email, Payroll) VALUES (N'Bán Hàng                                          ', 2, N'BH001                                             ', N'Cao Vũ Trâm Anh                                                                                     ', CAST(N'1996-04-07' AS Date), N'Nam       ', N'Cà Mau                                                                                                                                                                                                  ', N'01675454671         ', N'tramanh@gmail.com                                 ', N'9,000,000 VND                                                                                       ')
INSERT NhanVien (Position, Level, EmployeeCode, FullName, YearofBirth, Sex, Address, Phone, Email, Payroll) VALUES (N'Bảo Vệ                                            ', 2, N'BV001                                             ', N'Lý Văn Cường                                                                                        ', CAST(N'1996-04-29' AS Date), N'Nam       ', N'Hậu Giang                                                                                                                                                                                               ', N'01695452671         ', N'cuong@gmail.com                                   ', N'7,000,000 VND                                                                                       ')
INSERT NhanVien (Position, Level, EmployeeCode, FullName, YearofBirth, Sex, Address, Phone, Email, Payroll) VALUES (N'Nhân Viên Tư Vấn                                  ', 3, N'TV001                                             ', N'Lâm Như Ngọc                                                                                        ', CAST(N'1995-04-18' AS Date), N'Nam       ', N'Long An                                                                                                                                                                                                 ', N'01686527651         ', N'ngoc@gmail.com                                    ', N'12,000,000 VND                                                                                      ')
INSERT NhanVien (Position, Level, EmployeeCode, FullName, YearofBirth, Sex, Address, Phone, Email, Payroll) VALUES (N'Tạp Vụ                                            ', 3, N'TV002                                             ', N'Dương Văn Cường                                                                                     ', CAST(N'1994-04-20' AS Date), N'Nam       ', N'Sóc Trăng                                                                                                                                                                                               ', N'01687364657         ', N'cuong@gmail.com                                   ', N'9,600,000 VND                                                                                       ')
INSERT NhanVien (Position, Level, EmployeeCode, FullName, YearofBirth, Sex, Address, Phone, Email, Payroll) VALUES (N'Thủ Kho                                           ', 3, N'TK001                                             ', N'Huỳnh Thị Chúc Ly                                                                                   ', CAST(N'2018-04-30' AS Date), N'Nử        ', N'Sóc Trăng                                                                                                                                                                                               ', N'01686735461         ', N'ly@gmail.com                                      ', N'14,400,000 VND                                                                                      ')
INSERT NhanVien (Position, Level, EmployeeCode, FullName, YearofBirth, Sex, Address, Phone, Email, Payroll) VALUES (N'Nhân Viên Tiếp Thị                                ', 2, N'TT001                                             ', N'Nguyễn Văn A                                                                                        ', CAST(N'2018-05-02' AS Date), N'Nam       ', N'Cần Thơ                                                                                                                                                                                                 ', N'01684676781         ', N'vana@gmail.com                                    ', N'6,000,000 VND                                                                                       ')
INSERT NhanVien (Position, Level, EmployeeCode, FullName, YearofBirth, Sex, Address, Phone, Email, Payroll) VALUES (N'Bán Hàng                                          ', 3, N'BH0011                                            ', N'Cao Ngọc Vũ Trân                                                                                    ', CAST(N'2018-05-08' AS Date), N'Nử        ', N'Cần Thơ                                                                                                                                                                                                 ', N'01684342451         ', N'ngoc@gmail.com                                    ', N'13,500,000 VND                                                                                      ')
GO
INSERT Orders (ID, Customer, Address, Phone, Product, Amount, Price, WarrantyPeriod, intoMoney, Date, PaymentMethods) VALUES (N'DH001     ', N'Dương Thanh Trung                                 ', N'Hậu Giang                                                                                                                                                                                               ', N'01684342451         ', N'Ram 4GB                                                                                             ', 3, N'1,700,000 VND                                                                                       ', N'3 Năm                                                                                               ', N'5,100,000 VND                                                                                       ', CAST(N'2018-04-28' AS Date), N'Chuyển khoản                                                                                        ')
INSERT Orders (ID, Customer, Address, Phone, Product, Amount, Price, WarrantyPeriod, intoMoney, Date, PaymentMethods) VALUES (N'DH002     ', N'Nguyễn Hoàng Lộc                                  ', N'Sóc Trăng                                                                                                                                                                                               ', N'01645676751         ', N'X-Mobile                                                                                            ', 3, N'250,000 VND                                                                                         ', N'6 Tháng                                                                                             ', N'750,000 VND                                                                                         ', CAST(N'2018-04-29' AS Date), N'Chuyển khoản                                                                                        ')
INSERT Orders (ID, Customer, Address, Phone, Product, Amount, Price, WarrantyPeriod, intoMoney, Date, PaymentMethods) VALUES (N'DH004     ', N'Lê Quang Huy                                      ', N'Trà Vinh                                                                                                                                                                                                ', N'01684345431         ', N'CPU Core i7                                                                                         ', 5, N'2,000,000 VND                                                                                       ', N'4 Năm                                                                                               ', N'10,000,000 VND                                                                                      ', CAST(N'2018-04-30' AS Date), N'Chuyển khoản                                                                                        ')
INSERT Orders (ID, Customer, Address, Phone, Product, Amount, Price, WarrantyPeriod, intoMoney, Date, PaymentMethods) VALUES (N'DH005     ', N'Nguyễn Văn A                                      ', N'Cần Thơ                                                                                                                                                                                                 ', N'01684342471         ', N'X-Mobile                                                                                            ', 8, N'250,000 VND                                                                                         ', N'6 Tháng                                                                                             ', N'2,000,000 VND                                                                                       ', CAST(N'2018-05-03' AS Date), N'Nhận hàng trả tiền                                                                                  ')
INSERT Orders (ID, Customer, Address, Phone, Product, Amount, Price, WarrantyPeriod, intoMoney, Date, PaymentMethods) VALUES (N'HK005     ', N'Dương Văn Âu                                      ', N'Cần Thơ                                                                                                                                                                                                 ', N'01684342451         ', N'CPU i5                                                                                              ', 2, N'7,000,000 VND                                                                                       ', N'4 Năm                                                                                               ', N'14,000,000 VND                                                                                      ', CAST(N'2018-05-09' AS Date), N'Chuyển khoản                                                                                        ')
INSERT Orders (ID, Customer, Address, Phone, Product, Amount, Price, WarrantyPeriod, intoMoney, Date, PaymentMethods) VALUES (N'DH003     ', N'Tiêu Yến Nhi                                      ', N'Cần Thơ                                                                                                                                                                                                 ', N'01687556542         ', N'Pin Samsung                                                                                         ', 3, N'500,000 VND                                                                                         ', N'1 Năm                                                                                               ', N'1,500,000 VND                                                                                       ', CAST(N'2018-04-30' AS Date), N'Chuyển khoản                                                                                        ')
INSERT Orders (ID, Customer, Address, Phone, Product, Amount, Price, WarrantyPeriod, intoMoney, Date, PaymentMethods) VALUES (N'123123123 ', N'123123123                                         ', N'12312312                                                                                                                                                                                                ', N'3123123123          ', N'Tai Nghe Thế Hệ Mới                                                                                 ', 4, N'300,000 VND                                                                                         ', N'8 Tháng                                                                                             ', N'1,200,000 VND                                                                                       ', CAST(N'2020-05-06' AS Date), N'Nhận hàng trả tiền                                                                                  ')
INSERT Orders (ID, Customer, Address, Phone, Product, Amount, Price, WarrantyPeriod, intoMoney, Date, PaymentMethods) VALUES (N'123123    ', N'1231231323123                                     ', N'zxccccccccc                                                                                                                                                                                             ', N'131231              ', N'Hard Drive Kingston 120GB                                                                           ', 12331, N'3,500,000 VND                                                                                       ', N'5 Năm                                                                                               ', N'43,158,500,000 VND                                                                                  ', CAST(N'2020-05-06' AS Date), N'Chuyển khoản                                                                                        ')
GO
INSERT Position (ID, Position, Payroll) VALUES (N'BH01                ', N'Bán Hàng                                                                                                                                                                                                ', N'4,500,000 VND                                                                                                                                                                                           ')
INSERT Position (ID, Position, Payroll) VALUES (N'BV01                ', N'Bảo Vệ                                                                                                                                                                                                  ', N'3,500,000 VND                                                                                                                                                                                           ')
INSERT Position (ID, Position, Payroll) VALUES (N'GD001               ', N'Giám Đốc                                                                                                                                                                                                ', N'20,000,000 VND                                                                                                                                                                                          ')
INSERT Position (ID, Position, Payroll) VALUES (N'KT01                ', N'Kế Toán                                                                                                                                                                                                 ', N'5,000,000 VND                                                                                                                                                                                           ')
INSERT Position (ID, Position, Payroll) VALUES (N'TK01                ', N'Thủ Kho                                                                                                                                                                                                 ', N'4,800,000 VND                                                                                                                                                                                           ')
INSERT Position (ID, Position, Payroll) VALUES (N'TN01                ', N'Thu Ngân                                                                                                                                                                                                ', N'4,500,000 VND                                                                                                                                                                                           ')
INSERT Position (ID, Position, Payroll) VALUES (N'TT001               ', N'Tiếp Tân                                                                                                                                                                                                ', N'8,000,000 VND                                                                                                                                                                                           ')
INSERT Position (ID, Position, Payroll) VALUES (N'TT01                ', N'Nhân Viên Tiếp Thị                                                                                                                                                                                      ', N'3,000,000 VND                                                                                                                                                                                           ')
INSERT Position (ID, Position, Payroll) VALUES (N'TV01                ', N'Nhân Viên Tư Vấn                                                                                                                                                                                        ', N'4,000,000 VND                                                                                                                                                                                           ')
INSERT Position (ID, Position, Payroll) VALUES (N'TV02                ', N'Tạp Vụ                                                                                                                                                                                                  ', N'3,200,000 VND                                                                                                                                                                                           ')
GO
INSERT Producer (ID, ProducerName, Address, Phone, Email) VALUES (N'A001                          ', N'Asus                                              ', N'Tiền Giang                                                                                          ', N'09898989898         ', N'Asus@gmail.com                                    ')
INSERT Producer (ID, ProducerName, Address, Phone, Email) VALUES (N'J001                          ', N'JBL                                               ', N'Cà Mau                                                                                              ', N'0900009838          ', N'jbl@jbl.com.vn                                    ')
INSERT Producer (ID, ProducerName, Address, Phone, Email) VALUES (N'LT005                         ', N'Logitech                                          ', N'An giang                                                                                            ', N'0900990987          ', N'logitach@gmail.com                                ')
INSERT Producer (ID, ProducerName, Address, Phone, Email) VALUES (N'21231                         ', N'xxxxxxxxxxxx                                      ', N'1231231                                                                                             ', N'132222222           ', N'12312123                                          ')
INSERT Producer (ID, ProducerName, Address, Phone, Email) VALUES (N'M001                          ', N'Mobiistar                                         ', N'Yên Bái                                                                                             ', N'0900097460          ', N'mbt@mobiistar.com.vn                              ')
INSERT Producer (ID, ProducerName, Address, Phone, Email) VALUES (N'M010                          ', N'Microsoft                                         ', N'Hải Phòng                                                                                           ', N'0900090000          ', N'Microsoft@gmail.com                               ')
INSERT Producer (ID, ProducerName, Address, Phone, Email) VALUES (N'N000                          ', N'HP                                                ', N'Hậu Giang                                                                                           ', N'01670000021         ', N'hp@hg.email.vn                                    ')
INSERT Producer (ID, ProducerName, Address, Phone, Email) VALUES (N'N001                          ', N'Intel                                             ', N'Cần Thơ                                                                                             ', N'0909090909          ', N'intel@gmail.com                                   ')
INSERT Producer (ID, ProducerName, Address, Phone, Email) VALUES (N'N003                          ', N'Samsung                                           ', N'TP HCM                                                                                              ', N'0900090909          ', N'samsung@ss.com.vn                                 ')
INSERT Producer (ID, ProducerName, Address, Phone, Email) VALUES (N'N022                          ', N'Dell                                              ', N'Hà Nội                                                                                              ', N'0890092900          ', N'dell@dell.com.vn                                  ')
INSERT Producer (ID, ProducerName, Address, Phone, Email) VALUES (N'R001                          ', N'Kingston                                          ', N'Mỹ                                                                                                  ', N'02100002829         ', N'Kingston@gmail.com                                ')
INSERT Producer (ID, ProducerName, Address, Phone, Email) VALUES (N'R002                          ', N'G.SKILL                                           ', N'Đài Loan                                                                                            ', N'02390039393039      ', N'G.SKILL@gmail.com.vn                              ')
INSERT Producer (ID, ProducerName, Address, Phone, Email) VALUES (N'R003                          ', N'Corsair                                           ', N'Nga                                                                                                 ', N'03000494984         ', N'Corsair@gmail.com.vn                              ')
GO
INSERT Products (ID, Classify, Name, Producer, WarrantyPeriod, SingleTime, QuantityRemaining, Unit, Price, Path) VALUES (N'R001                          ', N'Ram                           ', N'Ram 4GB                                                                                             ', N'Kingston                                                                                            ', 3, N'Năm                           ', 91, N'Cái                           ', N'1,700,000 VND                                                                                       ', N'C:\Users\D.Thanh Trung\Documents\NetBeansProjects\Quan Ly Cua Hang Mua Ban Thiet Bi Dien Tu\src\Product Image\RAM 4GB.jpg                                                                                                                                                                                                                                                                                                                                                                                           ')
INSERT Products (ID, Classify, Name, Producer, WarrantyPeriod, SingleTime, QuantityRemaining, Unit, Price, Path) VALUES (N'PN001                         ', N'The Battery                   ', N'Pin Samsung                                                                                         ', N'Asus                                                                                                ', 1, N'Năm                           ', 74, N'Cục                           ', N'500,000 VND                                                                                         ', N'C:\Users\D.Thanh Trung\Documents\NetBeansProjects\Quan Ly Cua Hang Mua Ban Thiet Bi Dien Tu\src\Product Image\Pin SamSung.png                                                                                                                                                                                                                                                                                                                                                                                       ')
INSERT Products (ID, Classify, Name, Producer, WarrantyPeriod, SingleTime, QuantityRemaining, Unit, Price, Path) VALUES (N'XM001                         ', N'The Battery                   ', N'X-Mobile                                                                                            ', N'Kingston                                                                                            ', 6, N'Tháng                         ', 293, N'Cục                           ', N'250,000 VND                                                                                         ', N'C:\Users\D.Thanh Trung\Documents\NetBeansProjects\Quan Ly Cua Hang Mua Ban Thiet Bi Dien Tu\src\Product Image\Pin X-Mobile.jpg                                                                                                                                                                                                                                                                                                                                                                                      ')
INSERT Products (ID, Classify, Name, Producer, WarrantyPeriod, SingleTime, QuantityRemaining, Unit, Price, Path) VALUES (N'CP001                         ', N'CPU                           ', N'CPU Core i7                                                                                         ', N'Intel                                                                                               ', 4, N'Năm                           ', 80, N'Cái                           ', N'2,000,000 VND                                                                                       ', N'C:\Users\D.Thanh Trung\Documents\NetBeansProjects\Quan Ly Cua Hang Mua Ban Thiet Bi Dien Tu\src\Product Image\CPU Core i7.jpg                                                                                                                                                                                                                                                                                                                                                                                       ')
INSERT Products (ID, Classify, Name, Producer, WarrantyPeriod, SingleTime, QuantityRemaining, Unit, Price, Path) VALUES (N'KB001                         ', N'Keyboard                      ', N'Bàn Phím                                                                                            ', N'Logitech                                                                                            ', 1, N'Năm                           ', 96, N'Cái                           ', N'200,000 VND                                                                                         ', N'C:\Users\D.Thanh Trung\Documents\NetBeansProjects\Quan Ly Cua Hang Mua Ban Thiet Bi Dien Tu\src\Product Image\KeyBoard Logitech.jpg                                                                                                                                                                                                                                                                                                                                                                                 ')
INSERT Products (ID, Classify, Name, Producer, WarrantyPeriod, SingleTime, QuantityRemaining, Unit, Price, Path) VALUES (N'R0012                         ', N'USB                           ', N'HP 16GB                                                                                             ', N'HP                                                                                                  ', 1, N'Năm                           ', 100, N'Cái                           ', N'350,000 VND                                                                                         ', N'C:\Users\D.Thanh Trung\Documents\NetBeansProjects\Quan Ly Cua Hang Mua Ban Thiet Bi Dien Tu\src\Product Image\USB HP 16GB.jpg                                                                                                                                                                                                                                                                                                                                                                                       ')
INSERT Products (ID, Classify, Name, Producer, WarrantyPeriod, SingleTime, QuantityRemaining, Unit, Price, Path) VALUES (N'HP001                         ', N'Headphone                     ', N'Tai Nghe Thế Hệ Mới                                                                                 ', N'Asus                                                                                                ', 8, N'Tháng                         ', 98, N'Cái                           ', N'300,000 VND                                                                                         ', N'C:\Users\D.Thanh Trung\Documents\NetBeansProjects\Quan Ly Cua Hang Mua Ban Thiet Bi Dien Tu\src\Product Image\Tai Nghe JBL T450BT.jpg                                                                                                                                                                                                                                                                                                                                                                               ')
INSERT Products (ID, Classify, Name, Producer, WarrantyPeriod, SingleTime, QuantityRemaining, Unit, Price, Path) VALUES (N'HW001                         ', N'Hard Drive                    ', N'Hard Drive Kingston 120GB                                                                           ', N'Kingston                                                                                            ', 5, N'Năm                           ', 288, N'Cái                           ', N'3,500,000 VND                                                                                       ', N'C:\Users\D.Thanh Trung\Documents\NetBeansProjects\Quan Ly Cua Hang Mua Ban Thiet Bi Dien Tu\src\Product Image\Hard Drive Kingston 120GB.png                                                                                                                                                                                                                                                                                                                                                                         ')
INSERT Products (ID, Classify, Name, Producer, WarrantyPeriod, SingleTime, QuantityRemaining, Unit, Price, Path) VALUES (N'BL001                         ', N'Backpack                      ', N'Ba Lô 1                                                                                             ', N'JBL                                                                                                 ', 8, N'Tháng                         ', 300, N'Cái                           ', N'500,000 VND                                                                                         ', N'C:\Users\D.Thanh Trung\Documents\NetBeansProjects\Quan Ly Cua Hang Mua Ban Thiet Bi Dien Tu\src\Product Image\Balo 1.png                                                                                                                                                                                                                                                                                                                                                                                            ')
INSERT Products (ID, Classify, Name, Producer, WarrantyPeriod, SingleTime, QuantityRemaining, Unit, Price, Path) VALUES (N'BL002                         ', N'Backpack                      ', N'Ba Lô 2                                                                                             ', N'JBL                                                                                                 ', 1, N'Năm                           ', 50, N'Cái                           ', N'800,000 VND                                                                                         ', N'C:\Users\D.Thanh Trung\Documents\NetBeansProjects\Quan Ly Cua Hang Mua Ban Thiet Bi Dien Tu\src\Product Image\Balo 2.png                                                                                                                                                                                                                                                                                                                                                                                            ')
INSERT Products (ID, Classify, Name, Producer, WarrantyPeriod, SingleTime, QuantityRemaining, Unit, Price, Path) VALUES (N'CPU01                         ', N'CPU                           ', N'CPU intel i5                                                                                        ', N'Intel                                                                                               ', 4, N'Năm                           ', 200, N'Cái                           ', N'5,000,000 VND                                                                                       ', N'C:\Users\D.Thanh Trung\Documents\NetBeansProjects\Quan Ly Cua Hang Mua Ban Thiet Bi Dien Tu\src\Product Image\Cpu intel Core i5.jpg                                                                                                                                                                                                                                                                                                                                                                                 ')
INSERT Products (ID, Classify, Name, Producer, WarrantyPeriod, SingleTime, QuantityRemaining, Unit, Price, Path) VALUES (N'M001                          ', N'Mouse                         ', N'Mouse Genius Blue                                                                                   ', N'JBL                                                                                                 ', 8, N'Tháng                         ', 300, N'Cái                           ', N'200,000 VND                                                                                         ', N'C:\Users\D.Thanh Trung\Documents\NetBeansProjects\Quan Ly Cua Hang Mua Ban Thiet Bi Dien Tu\src\Product Image\Mouse Genius Blue.jpg                                                                                                                                                                                                                                                                                                                                                                                 ')
INSERT Products (ID, Classify, Name, Producer, WarrantyPeriod, SingleTime, QuantityRemaining, Unit, Price, Path) VALUES (N'M002                          ', N'Mouse                         ', N'Mouse Logitech                                                                                      ', N'Logitech                                                                                            ', 1, N'Năm                           ', 300, N'Cái                           ', N'350,000 VND                                                                                         ', N'C:\Users\D.Thanh Trung\Documents\NetBeansProjects\Quan Ly Cua Hang Mua Ban Thiet Bi Dien Tu\src\Product Image\Mouse Logitech.jpg                                                                                                                                                                                                                                                                                                                                                                                    ')
INSERT Products (ID, Classify, Name, Producer, WarrantyPeriod, SingleTime, QuantityRemaining, Unit, Price, Path) VALUES (N'U001                          ', N'USB                           ', N'USB HP 8GB                                                                                          ', N'HP                                                                                                  ', 2, N'Năm                           ', 100, N'Cái                           ', N'350,000 VND                                                                                         ', N'C:\Users\D.Thanh Trung\Documents\NetBeansProjects\Quan Ly Cua Hang Mua Ban Thiet Bi Dien Tu\src\Product Image\USB HP 8GB .jpg                                                                                                                                                                                                                                                                                                                                                                                       ')
INSERT Products (ID, Classify, Name, Producer, WarrantyPeriod, SingleTime, QuantityRemaining, Unit, Price, Path) VALUES (N'U002                          ', N'USB                           ', N'USB HP 16GB                                                                                         ', N'HP                                                                                                  ', 3, N'Ngày                          ', 200, N'Cái                           ', N'400,000 VND                                                                                         ', N'C:\Users\D.Thanh Trung\Documents\NetBeansProjects\Quan Ly Cua Hang Mua Ban Thiet Bi Dien Tu\src\Product Image\USB HP 16GB.jpg                                                                                                                                                                                                                                                                                                                                                                                       ')
INSERT Products (ID, Classify, Name, Producer, WarrantyPeriod, SingleTime, QuantityRemaining, Unit, Price, Path) VALUES (N'CP011                         ', N'CPU                           ', N'CPU i5                                                                                              ', N'Asus                                                                                                ', 4, N'Năm                           ', 498, N'Cái                           ', N'7,000,000 VND                                                                                       ', N'C:\Users\D.Thanh Trung\Documents\NetBeansProjects\Quan Ly Cua Hang Mua Ban Thiet Bi Dien Tu\src\Product Image\CPU Core i5.jpg                                                                                                                                                                                                                                                                                                                                                                                       ')
INSERT Products (ID, Classify, Name, Producer, WarrantyPeriod, SingleTime, QuantityRemaining, Unit, Price, Path) VALUES (N'R005                          ', N'Backpack                      ', N'RAM 2GB                                                                                             ', N'Asus                                                                                                ', 3, N'Năm                           ', 300, N'Cái                           ', N'800,000 VND                                                                                         ', N'C:\Users\D.Thanh Trung\Documents\NetBeansProjects\Quan Ly Cua Hang Mua Ban Thiet Bi Dien Tu\src\Product Image\RAM 2GB.jpg                                                                                                                                                                                                                                                                                                                                                                                           ')
GO
INSERT Revenue (Name, Date, Time, TotalMoney, Money, Surplus) VALUES (N'Điện Tử Số 1                                                                                        ', CAST(N'2018-04-28' AS Date), N'21:33:04                      ', N'5,100,000 VND                                                                                       ', N'6,000,000 VND                                                                                       ', N'900,000 VND                                                                                         ')
INSERT Revenue (Name, Date, Time, TotalMoney, Money, Surplus) VALUES (N'Dương Thanh Trung                                                                                   ', CAST(N'2018-03-25' AS Date), N'21:00:00                      ', N'5,100,000 VND                                                                                       ', N'6,000,000 VND                                                                                       ', N'900,000 VND                                                                                         ')
INSERT Revenue (Name, Date, Time, TotalMoney, Money, Surplus) VALUES (N'Nguyễn Hoàng Lộc                                                                                    ', CAST(N'2018-04-15' AS Date), N'14:00:00                      ', N'2,000,000 VND                                                                                       ', N'2,000,000 VND                                                                                       ', N'0 VND                                                                                               ')
INSERT Revenue (Name, Date, Time, TotalMoney, Money, Surplus) VALUES (N'Điện Tử Số 1', CAST(N'2018-04-29' AS Date), N'21:21:51', N'3,900,000 VND', N'4,000,000 VND', N'100,000 VND')
INSERT Revenue (Name, Date, Time, TotalMoney, Money, Surplus) VALUES (N'Nguyễn Hoàng Lộc', CAST(N'2018-04-30' AS Date), N'09:06:23', N'17,500,000 VND', N'20,000,000 VND', N'2,500,000 VND')
INSERT Revenue (Name, Date, Time, TotalMoney, Money, Surplus) VALUES (N'Dương Thanh Trung', CAST(N'2018-04-30' AS Date), N'21:07:47', N'10,000,000 VND', N'12,000,000 VND', N'2,000,000 VND')
INSERT Revenue (Name, Date, Time, TotalMoney, Money, Surplus) VALUES (N'Dương Thanh Trung', CAST(N'2018-05-03' AS Date), N'19:54:14', N'10,000,000 VND', N'10,000,000 VND', N'0 VND')
INSERT Revenue (Name, Date, Time, TotalMoney, Money, Surplus) VALUES (N'Dương Thanh Trung', CAST(N'2018-05-05' AS Date), N'07:47:14', N'3,900,000 VND', N'4,500,000 VND', N'600,000 VND')
INSERT Revenue (Name, Date, Time, TotalMoney, Money, Surplus) VALUES (N'Dương Thanh Trung', CAST(N'2018-05-05' AS Date), N'07:50:42', N'5,350,000 VND', N'5,500,000 VND', N'150,000 VND')
INSERT Revenue (Name, Date, Time, TotalMoney, Money, Surplus) VALUES (N'Dương Thanh Trung', CAST(N'2018-05-06' AS Date), N'12:48:12', N'18,000,000 VND', N'20,000,000 VND', N'2,000,000 VND')
INSERT Revenue (Name, Date, Time, TotalMoney, Money, Surplus) VALUES (N'Điện Tử Số 1', CAST(N'2018-05-06' AS Date), N'13:17:16', N'4,000,000 VND', N'4,500,000 VND', N'500,000 VND')
INSERT Revenue (Name, Date, Time, TotalMoney, Money, Surplus) VALUES (N'Điện Tử Số 1', CAST(N'2020-05-11' AS Date), N'16:28:08', N'10,500,000 VND', N'33,333,333 VND', N'22,833,333 VND')
INSERT Revenue (Name, Date, Time, TotalMoney, Money, Surplus) VALUES (N'Điện Tử Số 1', CAST(N'2020-05-11' AS Date), N'16:29:15', N'10,500,000 VND', N'33,333,333 VND', N'22,833,333 VND')
INSERT Revenue (Name, Date, Time, TotalMoney, Money, Surplus) VALUES (N'Điện Tử Số 1', CAST(N'2020-05-11' AS Date), N'16:31:23', N'10,500,000 VND', N'44,444,444 VND', N'33,944,444 VND')
INSERT Revenue (Name, Date, Time, TotalMoney, Money, Surplus) VALUES (N'Điện Tử Số 1', CAST(N'2020-05-11' AS Date), N'16:32:17', N'10,500,000 VND', N'12,312,313,123 VND', N'12,301,813,123 VND')
INSERT Revenue (Name, Date, Time, TotalMoney, Money, Surplus) VALUES (N'Dương Thanh Trung', CAST(N'2018-05-03' AS Date), N'20:39:28', N'1,000,000 VND', N'1,200,000 VND', N'200,000 VND')
INSERT Revenue (Name, Date, Time, TotalMoney, Money, Surplus) VALUES (N'Điện Tử Số 1', CAST(N'2018-05-05' AS Date), N'07:45:40', N'3,900,000 VND', N'4,500,000 VND', N'600,000 VND')
INSERT Revenue (Name, Date, Time, TotalMoney, Money, Surplus) VALUES (N'Dương Thanh Trung', CAST(N'2018-05-07' AS Date), N'10:14:58', N'14,000,000 VND', N'15,000,000 VND', N'1,000,000 VND')
GO
INSERT ThongKe (Name, Date, Time, TotalMoney, Money, Surplus) VALUES (N'Dương Thanh Trung', CAST(N'2018-05-03' AS Date), N'19:54:14', N'10,000,000 VND', N'10,000,000 VND', N'0 VND')
INSERT ThongKe (Name, Date, Time, TotalMoney, Money, Surplus) VALUES (N'Dương Thanh Trung', CAST(N'2018-05-05' AS Date), N'07:47:14', N'3,900,000 VND', N'4,500,000 VND', N'600,000 VND')
INSERT ThongKe (Name, Date, Time, TotalMoney, Money, Surplus) VALUES (N'Dương Thanh Trung', CAST(N'2018-05-05' AS Date), N'07:50:42', N'5,350,000 VND', N'5,500,000 VND', N'150,000 VND')
INSERT ThongKe (Name, Date, Time, TotalMoney, Money, Surplus) VALUES (N'Dương Thanh Trung', CAST(N'2018-05-06' AS Date), N'12:48:12', N'18,000,000 VND', N'20,000,000 VND', N'2,000,000 VND')
INSERT ThongKe (Name, Date, Time, TotalMoney, Money, Surplus) VALUES (N'Điện Tử Số 1', CAST(N'2018-05-06' AS Date), N'13:17:16', N'4,000,000 VND', N'4,500,000 VND', N'500,000 VND')
INSERT ThongKe (Name, Date, Time, TotalMoney, Money, Surplus) VALUES (N'Dương Thanh Trung', CAST(N'2018-05-03' AS Date), N'20:39:28', N'1,000,000 VND', N'1,200,000 VND', N'200,000 VND')
INSERT ThongKe (Name, Date, Time, TotalMoney, Money, Surplus) VALUES (N'Điện Tử Số 1', CAST(N'2018-05-05' AS Date), N'07:45:40', N'3,900,000 VND', N'4,500,000 VND', N'600,000 VND')
INSERT ThongKe (Name, Date, Time, TotalMoney, Money, Surplus) VALUES (N'Dương Thanh Trung', CAST(N'2018-05-07' AS Date), N'10:14:58', N'14,000,000 VND', N'15,000,000 VND', N'1,000,000 VND')
GO